### ISSUE TITLE
No file of "pytorch_ipynb/mlp/mlp-sequential.ipynb"

### ISSUE THREAD

**Issue by LZP4GitHub** [rasbt/deeplearning-models#13]
In the folder of  `pytorch_ipynb/mlp`,I can't find the file "Sequential API and hooks [PyTorch]“.

**Comment by rasbt** [comment]
Thanks for the note. It should have been /mechanics not /mlp. Just fixed that link: https://github.com/rasbt/deeplearning-models/blob/master/pytorch_ipynb/mechanics/mlp-sequential.ipynb
