### ISSUE TITLE
The out channel number in cnn_basic pytorch

### ISSUE THREAD

**Issue by elliotcoupe** [rasbt/deeplearning-models#16]
# 28x28x1 => 28x28x4
        self.conv_1 = torch.nn.Conv2d(in_channels=1,
                                      out_channels=8,
The out_channels = 8 shouldn't it become 28x28x8

**Comment by rasbt** [comment]
ah yes, i probably changed the code some time but forgot the change the comments ...

**Comment by rasbt** [comment]
Forgot to close it when I fixed the comments a few months back ...
