### ISSUE TITLE
Questions about the book

### ISSUE THREAD

**Issue by limt15** [rasbt/deeplearning-models#27]
Dear author, thank you for offering the code.

But I can't open the ebook link `https://leanpub.com/ann-and-deeplearning`

Could you please send me the pdf of the book?
My email address is `mtli@stu.ecnu.edu.cn`

Thank you very much!

**Comment by rasbt** [comment]
Hi there,

this link currently doesn't exist. I just see that there are 4 notebooks that contain a link to Leanpub (https://github.com/rasbt/deeplearning-models/search?q=leanpub.com&unscoped_q=leanpub.com) -- sorry about the confusion, will fix that.

**Comment by limt15** [comment]
Hi, thank very much!
But I still cannot get the pdf of the book, It seems that the `download` option doesn't exist on the book page.
How can I get this book?

**Comment by rasbt** [comment]
Sorry about that but the book is not finished and thus not available online
