### ISSUE TITLE
Convolutional Conditional Variational Autoencoder with label in recon loss is bad

### ISSUE THREAD

**Issue by Johnson-yue** [rasbt/deeplearning-models#34]
Hi， I check your Notebook but， the preformance is very bad right？  why？

**Comment by rasbt** [comment]
I don't know. It works fine for the non-convolutional (fully connected) VAE. I suspect that's because if you add the reconstruction labels in the conv. variant, some of the structure of the embedding is lost.

**Comment by Johnson-yue** [comment]
the fully connected is very simple and the mnist is also simple dataset，So， you can use any resolution to fix it，but using convolution it is more complex ， so， it should be more tricky to fix it。

Maybe the gradient of network is bad ？

**Comment by rasbt** [comment]
maybe. but there is no bug in the code, I think. The same architecture works fine when the labels are not concatenated with the image to compute the reconstruction loss. Also, the general approach (concatenating) works fine for fully connected ones. 

 Maybe this just needs some more hyperparam tuning.

**Comment by Johnson-yue** [comment]
yes, I think so , would you plan to add other dataset, Maybe like ,CIFAR-10, tiny-Imagenet?

**Comment by rasbt** [comment]
yeah, one day :). There are many things that could be added. This would be interesting to try to investigate how well this approach works on RGB images

**Comment by Johnson-yue** [comment]
thanks for your sharing
