### ISSUE TITLE
Imbalanced Classes

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [rasbt/deeplearning-models#37]
Hi,
Does this implementation solves any class imbalanced datasets ? Since of the features of Celeba dataset has high class imbalance, does your solution addresses this issue ?

**Comment by rasbt** [comment]
Hi there,

good question! We did account for class imbalance in a research project where we used CelebA (https://arxiv.org/abs/1807.11936), but I didn't do anything regarding class imbalance in this repository. 

This was because in an earlier project where we developed a method for "fooling" a gender classifier, I found that the gender classifier can more easily be fooled if it is a picture of a male person. It may be because there are more female pictures in the dataset. Regarding skin color and gender, there was also some difference for males; however, I didn't see the difference they found in the "Gender Shades" (http://gendershades.org/overview.html) paper, which was published a few months afterwards. Anyways, here are some of the results I got back then ~2 years ago. This is for fooling the gender classifier, so an error of 0.5 is desired.

![Screen Shot 2020-01-27 at 10 16 53 AM](https://user-images.githubusercontent.com/5618407/73192334-81112500-40ee-11ea-8419-05381a43611e.png)

**Comment by SURABHI-GUPTA** [comment]
Hey,

Thank you for such a quick response. If possible, can you share the code
for addressing class imbalance for a feature, say Double_Chin, in celebA
?
It would be really helpful for me to understand.

Thanks and regards,

Surabhi Gupta

**Comment by rasbt** [comment]
Sry we haven't done that, we only oversampled by gender and skin color

**Comment by SURABHI-GUPTA** [comment]
Okay.
But when I ran your code over imbalanced features, it gave 95% accuracy on
test images. So, what can be the reason behind this ? Is it because the
samples of majority class are more ?

**Comment by rasbt** [comment]
it depends. On which labels (imbalanced features) did you do the prediction? And what's their ratio in the dataset?

**Comment by SURABHI-GUPTA** [comment]
I did it over 'Double_Chin' which has "Without Double_Chin"= 193140 images
and "With Double_Chin"= 9549 images
Number of DC and NDC images in training dataset: 7571 and 155199
Number of DC and NDC images in validation dataset: 975  and 18892
Number of DC and NDC images in testing dataset: 913 and 19049

**Comment by rasbt** [comment]
In that case, it could indeed have learned to always predict the majority label, because 

19049/(19049+913) = 0.954

**Comment by SURABHI-GUPTA** [comment]
Yes. True.

Any suggestion from your side on how can I handle this class imbalanced
situation ?

**Comment by rasbt** [comment]
The imbalances we were dealing with weren't that extreme so in our case oversampling and/or undersampling both worked fine. Not sure if that's true in your case though. 

You can maybe pre-train the network on a different attribute that is less imbalanced. Then, you can undersample your current dataset and use transfer learning to see if you get good results. It's a big imbalance though and getting good results may be tricky.

**Comment by SURABHI-GUPTA** [comment]
Okay. I will try that.

Thank you for you help and time.

**Comment by SURABHI-GUPTA** [comment]
Hi,

For handling imbalance, I tried to duplicate the rows of minority class in train.csv file itself. But I am getting an error while joining the paths:

Traceback (most recent call last):
  File "/home/surabhi/celeba-dataset/classify_bl_aug.py", line 302, in <module>
    model_conv = train_model(model_conv, optimizer_conv, exp_lr_scheduler, num_epochs=10)
  File "/home/surabhi/celeba-dataset/classify_bl_aug.py", line 207, in train_model
    for inputs, labels in dataloaders[phase]:
  File "/home/dataset/packages/pytorch/1.0.0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/dataset/packages/pytorch/1.0.0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/dataset/packages/pytorch/1.0.0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/dataset/packages/pytorch/1.0.0/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/surabhi/celeba-dataset/classify_bl_aug.py", line 69, in __getitem__
    img = Image.open(os.path.join(self.img_dir, self.img_names[index]))
  File "/home/dataset/packages/python/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/dataset/packages/python/3.7/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int64'
