### ISSUE TITLE
Question about conditional autoencoder

### ISSUE THREAD

**Issue by sparshgarg23** [rasbt/deeplearning-models#58]
Hi sebastian,
I have some questions about CVAE,hope you can help me understand 
So,rather than training CVAE on images,I am trying to train it on a  list of numpy arrays,each array contains 45 parameters.
As for my condition variable it consists of 33 parameters .
in all the training X's total size is 1500x43 and the condition variable's size is 33x3
Any ideas on what modifications I can do to run CVAE on my example.Basically I am trying to generate new values for each of the 45 parameters given the values in the condition variable.
Also,will a CVAE be a suitable choice for my case.

**Comment by rasbt** [comment]
From my experience, running VAEs on non-image data is notoriously difficult. The reason is that it is very hard to check whether it creates sensible results. Sure, you can look at the loss values, but it is still hard to tell compared to looking at image quality.

**Comment by sparshgarg23** [comment]
Thanks that sort of confirmed my earlier suspicion.
